import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#f3f4f6", // light gray background like mockup
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingTop: Platform.select({ ios: 50, android: 30, web: 20 }),
      paddingHorizontal: 20,
      paddingBottom: 16,
      backgroundColor: "#ffffff",
      borderBottomWidth: 1,
      borderBottomColor: "#e5e7eb",
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "#ffffff",
      justifyContent: "center",
      alignItems: "center",
    },
    headerCenter: {
      flex: 1,
      alignItems: "center",
    },
    headerTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: "#1a1a1a",
    },
    headerSubtitle: {
      fontSize: 12,
      color: "#6b7280",
      marginTop: 2,
    },
    exportBtn: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#ffffff",
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: "#6366f1",
      gap: 6,
    },
    exportText: {
      color: "#6366f1",
      fontSize: 14,
      fontWeight: "600",
    },
    videoSection: {
      paddingHorizontal: 20,
      flex: 1,
      justifyContent: 'center',
    },
  videoWrapper: {
    width: '100%',
    height: 240,
    backgroundColor: '#ffffff',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    // subtle shadow like mockup
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  bottomSection: {
    backgroundColor: '#f9fafb',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    paddingBottom: 96, // space for fixed toolbar
  },
    video: {
      width: "100%",
      aspectRatio: 16 / 9,
    },
    videoControls: {
      position: "absolute",
      bottom: 16,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "center",
      alignItems: "center",
      gap: 20,
    },
    controlButton: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: "rgba(0,0,0,0.7)",
      justifyContent: "center",
      alignItems: "center",
    },
    timelineSection: {
      backgroundColor: "#f9fafb",
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: "#e5e7eb",
    },
    timelineHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 20,
      marginBottom: 12,
    },
    timelineTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: "#1a1a1a",
    },
    timeDisplay: {
      backgroundColor: "#ffffff",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#e5e7eb',
    },
    timeText: {
      fontSize: 12,
      color: "#6b7280",
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    timeline: {
      paddingLeft: 20,
    },
    timelineTrack: {
      flexDirection: "row",
      alignItems: "center",
      gap: 2,
    },
    timelineSegment: {
      alignItems: "center",
      gap: 4,
    },
    segmentThumbnail: {
      width: 60,
      height: 40,
      backgroundColor: "#ffffff",
      borderRadius: 4,
      borderWidth: 1,
      borderColor: "#e5e7eb",
    },
    segmentTime: {
      fontSize: 10,
      color: "#6b7280",
    },
    toolsSection: {
      backgroundColor: "#f9fafb",
      paddingVertical: 16,
      borderTopWidth: 1,
      borderTopColor: "#e5e7eb",
    },
    toolsTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: "#1a1a1a",
      paddingHorizontal: 20,
      marginBottom: 16,
    },
    toolsContainer: {
      flexDirection: "row",
      paddingHorizontal: 20,
      justifyContent: 'space-between',
      flex: 1,
    },
    toolButton: {
      alignItems: "center",
      justifyContent: "center",
      width: 80,
      height: 72,
      borderRadius: 12,
      backgroundColor: "#ffffff",
      gap: 8,
      borderWidth: 1,
      borderColor: '#e5e7eb',
    },
    toolButtonActive: {
      backgroundColor: "#6366f1/20",
      borderWidth: 1,
      borderColor: "#6366f1",
    },
    toolLabel: {
      fontSize: 12,
      color: "#6b7280",
      fontWeight: "500",
    },
    toolLabelActive: {
      color: "#6366f1",
    },
    // Fixed toolbar pinned to bottom
    toolbarFixed: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: '#ffffff',
      borderTopWidth: 1,
      borderTopColor: '#e5e7eb',
      paddingVertical: 12,
    },
    controlsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 16,
      paddingVertical: 8,
    },
    controlTime: {
      fontSize: 12,
      color: '#6b7280',
      minWidth: 44,
      textAlign: 'center',
    },
    playButtonCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e5e7eb',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOpacity: 0.05,
      shadowRadius: 6,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    debugPanel: {
      marginTop: 8,
      marginHorizontal: 16,
      backgroundColor: '#ffffff',
      borderWidth: 1,
      borderColor: '#e5e7eb',
      borderRadius: 8,
      padding: 10,
    },
    debugText: {
      fontSize: 12,
      color: '#111827',
      fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    },
    center: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#0f0f0f",
      gap: 16,
    },
    errorText: {
      fontSize: 18,
      color: "#9ca3af",
      marginBottom: 8,
    },
    backButton: {
      backgroundColor: "#6366f1",
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 8,
    },
    backButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
    },
  })
  