import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#0f0f0f",
    },
    header: {
      paddingTop: Platform.select({ ios: 60, android: 40, web: 20 }),
      paddingHorizontal: 24,
      paddingBottom: 20,
      backgroundColor: "#1a1a1a",
      borderBottomWidth: 1,
      borderBottomColor: "#2a2a2a",
    },
    headerTitle: {
      fontSize: 28,
      fontWeight: "700",
      color: "#fff",
      marginBottom: 4,
    },
    headerSubtitle: {
      fontSize: 16,
      color: "#9ca3af",
      fontWeight: "400",
    },
    emptyState: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 24,
    },
    uploadArea: {
      alignItems: "center",
      backgroundColor: "#1a1a1a",
      borderRadius: 20,
      padding: 40,
      borderWidth: 2,
      borderColor: "#2a2a2a",
      borderStyle: "dashed",
      width: "100%",
      maxWidth: 400,
    },
    uploadIcon: {
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: "#6366f1",
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 24,
    },
    uploadTitle: {
      fontSize: 24,
      fontWeight: "600",
      color: "#fff",
      marginBottom: 8,
      textAlign: "center",
    },
    uploadSubtitle: {
      fontSize: 16,
      color: "#9ca3af",
      textAlign: "center",
      marginBottom: 32,
      lineHeight: 24,
    },
    selectButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#6366f1",
      paddingHorizontal: 24,
      paddingVertical: 14,
      borderRadius: 12,
      gap: 8,
    },
    selectButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
    },
    previewContainer: {
      flex: 1,
      padding: 24,
      gap: 24,
    },
    videoContainer: {
      position: "relative",
      borderRadius: 16,
      overflow: "hidden",
      backgroundColor: "#000",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 8,
    },
    video: {
      width: "100%",
      aspectRatio: 16 / 9,
    },
    videoOverlay: {
      position: "absolute",
      top: 16,
      left: 16,
      right: 16,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    videoInfo: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.7)",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      gap: 6,
    },
    videoInfoText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "500",
    },
    actionPanel: {
      gap: 12,
    },
    actionButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 16,
      paddingHorizontal: 24,
      borderRadius: 12,
      gap: 8,
    },
    primaryButton: {
      backgroundColor: "#6366f1",
    },
    primaryButtonText: {
      color: "#fff",
      fontSize: 16,
      fontWeight: "600",
    },
    secondaryButton: {
      backgroundColor: "#1a1a1a",
      borderWidth: 1,
      borderColor: "#2a2a2a",
    },
    secondaryButtonText: {
      color: "#9ca3af",
      fontSize: 16,
      fontWeight: "500",
    },
  })