import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  timelineContainer: {
    width: '100%',
    height: 140,
    backgroundColor: '#f9fafb',
    position: 'relative',
    paddingTop: 8,
    paddingBottom: 12,
  },
  track: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  indicator: {
    position: 'absolute',
    width: 2,
    top: 0,
    bottom: 0,
    backgroundColor: '#111827',
    left: '50%',
    transform: [{ translateX: -1 }],
  },
  content: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
  },
  overlayTimeline: {
    position: 'absolute',
    height: 32,
    backgroundColor: 'rgba(124, 58, 237, 0.12)',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#8b5cf6',
    top: 12, // center within 56px track
  },
  deleteButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#ef4444',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  handleLeft: {
    position: 'absolute',
    left: -6,
    top: 0,
    width: 12,
    height: '100%',
    backgroundColor: '#8b5cf6',
    borderTopLeftRadius: 6,
    borderBottomLeftRadius: 6,
  },
  handleRight: {
    position: 'absolute',
    right: -6,
    top: 0,
    width: 12,
    height: '100%',
    backgroundColor: '#8b5cf6',
    borderTopRightRadius: 6,
    borderBottomRightRadius: 6,
  },
  audioRow: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  audioText: {
    marginLeft: 8,
    color: '#6b7280',
    fontSize: 12,
  },
});
